development:
  adapter: postgresql
  encoding: unicode
  database: fandangr_development
  pool: 5
  username: sumeetjain
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: fandangr_test
  pool: 5
  username: sumeetjain
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: fandangr_production
  pool: 5
  username: sumeetjain
  password:
